export const sampleDashboard = {
  source: "sample",
  generatedAt: new Date().toISOString(),
  overview: {
    noteDetailSuccess: 90,
    noteDetailFailed: 110,
    assetSuccess: 90,
    vectorCount: 90,
    contentAssetSuccessRuns: 90,
    contentAssetFailedRuns: 6,
    minPublishTime: "2024-11-08T00:00:00.000Z",
    maxPublishTime: "2026-07-31T00:00:00.000Z",
  },
  contentInsight: {
    range: {
      start: "",
      end: "",
      minNoteDate: "2026-05-31T00:00:00.000Z",
      maxNoteDate: "2026-07-19T00:00:00.000Z",
      minCapturedAt: "2026-05-31T00:00:00.000Z",
      maxCapturedAt: "2026-07-19T00:00:00.000Z",
    },
    overview: {
      noteTotal: 90,
      interactionTotal: 128460,
      likeTotal: 82400,
      collectedTotal: 28600,
      commentsTotal: 8740,
      minNoteDate: "2026-05-31T00:00:00.000Z",
      maxNoteDate: "2026-07-19T00:00:00.000Z",
      minCapturedAt: "2026-05-31T00:00:00.000Z",
      maxCapturedAt: "2026-07-19T00:00:00.000Z",
    },
    topicFrequency: [
      { core_topic_category: "GEO避坑", note_count: 24, share_pct: 26.67 },
      { core_topic_category: "AI搜索优化", note_count: 19, share_pct: 21.11 },
      { core_topic_category: "品牌流量增长", note_count: 16, share_pct: 17.78 },
      { core_topic_category: "内容结构拆解", note_count: 13, share_pct: 14.44 },
      { core_topic_category: "搜索口碑治理", note_count: 10, share_pct: 11.11 },
      { core_topic_category: "行业案例复盘", note_count: 8, share_pct: 8.89 },
    ],
    personaDistribution: [
      { primary_target_persona: "垂直探路者", note_count: 36, share_pct: 40 },
      { primary_target_persona: "行业焦虑决策者", note_count: 28, share_pct: 31.11 },
      { primary_target_persona: "行业观望者", note_count: 18, share_pct: 20 },
      { primary_target_persona: "认知小白", note_count: 8, share_pct: 8.89 },
    ],
    noteAnalysis: [
      {
        note_id: "6a1ba9a10000000006031daa",
        title: "每天拆解一个运营知识-GEO排名优化",
        content_excerpt: "GEO 不只是把关键词塞进标题，而是让 AI 搜索能识别你的专业答案、案例证据和可信来源。先搭建内容资产，再用结构化表达把解决方案讲清楚。",
        author_nickname: "GEO增长研究所",
        note_date: "2026-05-31T00:00:00.000Z",
        captured_at: "2026-08-04T00:00:00.000Z",
        publish_time: "2026-05-31T00:00:00.000Z",
        note_type: "图文",
        core_topic_category: "GEO避坑",
        primary_target_persona: "垂直探路者",
        target_persona_tags: ["垂直探路者", "行业焦虑决策者"],
        target_persona_reason: "内容先解释操作路径，再给验证指标，适合已经准备试水 GEO 的运营和业务负责人。",
        primary_industry: "数字营销/内容运营",
        industry_tags: ["数字营销", "内容运营", "AI营销"],
        funnel_role: "信任",
        funnel_role_reason: "通过拆解方法论降低理解成本，帮助账号建立专业可信度。",
        like_count: 612,
        collected_count: 240,
        comments_count: 58,
        share_count: 18,
        interaction_score: 968,
        fresh_hot_score: 361.2,
        true_pain_label: "决策困难+效率问题",
        pain_description: "担心错过 AI 搜索流量入口，但不知道从哪里开始做。",
        pain_evidence: "评论区集中询问操作步骤、检测工具和投入优先级。",
        pain_authenticity: "真实痛点",
        pain_confidence: 0.86,
        business_relevance_score: 0.91,
        llm_confidence: 0.84,
        knowledge_points: [
          { point: "GEO 内容结构", explanation: "让模型识别结论、证据、场景和可信来源。", reuse_angle: "适合复用为教程型选题" },
        ],
        reusable_angles: [
          { angle: "从 SEO 到 GEO 的迁移清单", suitable_persona: "垂直探路者", suggested_funnel_role: "信任", why_it_works: "用旧认知承接新概念" },
        ],
        title_templates: ["{{行业}}做GEO前，先把这{{数字}}件事想清楚"],
        business_logic: "用清单式步骤把复杂概念拆成可执行动作。",
        content_logic: "先抛结论，再拆误区、步骤和验证指标。",
        hook_types: ["避坑", "清单"],
        cta_strategy: "适合引导用户领取检查清单或咨询诊断。",
        risk_flags: ["不要承诺绝对排名"],
        visual_group_style_prompt: "白底知识卡片，蓝黑正文，关键结论用浅黄色强调，高信息密度，适合小红书竖图教程。",
        visual_main_colors: "白色、蓝色、黑色、浅黄色",
        visual_emotion: "专业、可信、可执行",
        information_density_level: "高密度",
        information_density_reason: "单图承载结论、步骤和指标，文字较多但层级清晰。",
        layout_structure: "顶部抛结论，中部三步拆解，底部给行动检查项。",
        cover_text_logic: "用反常识标题打破只做 SEO 的旧认知。",
        asset_text_excerpt: "这条笔记适合沉淀为 GEO 入门教程资产，核心价值在于把抽象概念拆成业务可执行步骤。",
        note_url: "",
      },
      {
        note_id: "6a637720000000001c0103b3",
        title: "别再只做SEO，GEO才是AI新流量",
        content_excerpt: "AI 搜索正在改变品牌被发现的方式，内容不再只服务搜索引擎排名，也要服务模型生成答案时的引用和推荐。",
        author_nickname: "AI品牌观察",
        note_date: "2026-07-19T00:00:00.000Z",
        captured_at: "2026-08-03T00:00:00.000Z",
        publish_time: "2026-07-19T00:00:00.000Z",
        note_type: "图文",
        core_topic_category: "AI搜索优化",
        primary_target_persona: "行业观望者",
        target_persona_tags: ["行业观望者", "认知小白"],
        target_persona_reason: "内容更偏趋势科普，适合还在判断 GEO 投入价值的人。",
        primary_industry: "品牌营销",
        industry_tags: ["品牌营销", "AI营销"],
        funnel_role: "曝光",
        funnel_role_reason: "用新旧渠道对比扩大认知覆盖。",
        like_count: 25,
        collected_count: 9,
        comments_count: 4,
        share_count: 2,
        interaction_score: 42,
        fresh_hot_score: 11.0,
        true_pain_label: "机会错失",
        pain_description: "知道搜索入口变化，但还没判断投入优先级。",
        pain_evidence: "用户会关注 GEO 与 SEO 的投入差异。",
        pain_authenticity: "真实痛点",
        pain_confidence: 0.74,
        business_relevance_score: 0.78,
        llm_confidence: 0.8,
        knowledge_points: [{ point: "AI 搜索入口变化", explanation: "品牌内容需要适配模型答案生成。", reuse_angle: "趋势科普选题" }],
        reusable_angles: [{ angle: "SEO 与 GEO 对比", suitable_persona: "行业观望者", suggested_funnel_role: "曝光", why_it_works: "容易制造认知差" }],
        title_templates: ["别再只做{{旧渠道}}，{{新渠道}}才是新流量"],
        business_logic: "用新旧渠道对比制造认知差。",
        content_logic: "先对比 SEO 与 GEO，再给判断框架。",
        hook_types: ["信息差", "趋势"],
        cta_strategy: "适合引导继续阅读方法论内容。",
        risk_flags: ["避免制造过度焦虑"],
        visual_group_style_prompt: "白底黑字信息图，蓝色强调词，左右对比布局，中等信息密度。",
        visual_main_colors: "白色、黑色、蓝色",
        visual_emotion: "趋势感、理性判断",
        information_density_level: "中密度",
        information_density_reason: "主要呈现对比关系和少量结论。",
        layout_structure: "顶部提出趋势，中部左右对比，底部给判断标准。",
        cover_text_logic: "用否定旧方案突出新机会。",
        asset_text_excerpt: "这条笔记适合作为 GEO 趋势认知内容，承担曝光和教育市场的作用。",
        note_url: "",
      },
    ],
    trendDaily: [
      { bucket_date: "2026-07-13", note_count: 8, like_total: 5200, collected_total: 1800, comments_total: 360 },
      { bucket_date: "2026-07-14", note_count: 10, like_total: 6800, collected_total: 2400, comments_total: 420 },
      { bucket_date: "2026-07-15", note_count: 7, like_total: 4300, collected_total: 1600, comments_total: 310 },
      { bucket_date: "2026-07-16", note_count: 12, like_total: 7600, collected_total: 3100, comments_total: 540 },
      { bucket_date: "2026-07-17", note_count: 15, like_total: 9800, collected_total: 3900, comments_total: 690 },
      { bucket_date: "2026-07-18", note_count: 16, like_total: 11200, collected_total: 4200, comments_total: 730 },
      { bucket_date: "2026-07-19", note_count: 22, like_total: 13600, collected_total: 5200, comments_total: 920 },
    ],
    sparklineDaily: [
      { bucket_date: "2026-07-13", note_count: 8, like_total: 5200, collected_total: 1800, comments_total: 360 },
      { bucket_date: "2026-07-14", note_count: 10, like_total: 6800, collected_total: 2400, comments_total: 420 },
      { bucket_date: "2026-07-15", note_count: 7, like_total: 4300, collected_total: 1600, comments_total: 310 },
      { bucket_date: "2026-07-16", note_count: 12, like_total: 7600, collected_total: 3100, comments_total: 540 },
      { bucket_date: "2026-07-17", note_count: 15, like_total: 9800, collected_total: 3900, comments_total: 690 },
      { bucket_date: "2026-07-18", note_count: 16, like_total: 11200, collected_total: 4200, comments_total: 730 },
      { bucket_date: "2026-07-19", note_count: 22, like_total: 13600, collected_total: 5200, comments_total: 920 },
    ],
  },
  queueStatus: [{ status: "success", count: 199 }],
  topFresh: [
    {
      note_id: "6a1ba9a10000000006031daa",
      title: "每天拆解一个运营知识-GEO排名优化",
      publish_time: "2026-05-31T00:00:00.000Z",
      interaction_score: 968,
      fresh_hot_score: 361.2,
      true_pain_label: "决策困难+效率问题",
      primary_target_persona: "垂直探路者",
      target_persona_tags: ["垂直探路者", "行业观望者", "行业焦虑决策者"],
      primary_industry: "数字营销/内容运营",
      industry_tags: ["数字营销", "内容运营", "AI营销", "MarTech"],
      funnel_role: "信任",
    },
    {
      note_id: "6a637720000000001c0103b3",
      title: "别再只做SEO，GEO才是AI新流量",
      publish_time: "2026-07-19T00:00:00.000Z",
      interaction_score: 42,
      fresh_hot_score: 11.0,
      true_pain_label: "机会错失",
      primary_target_persona: "行业观望者",
      target_persona_tags: ["认知小白", "行业观望者"],
      primary_industry: "AI营销",
      industry_tags: ["AI营销", "品牌营销"],
      funnel_role: "曝光",
    },
  ],
  personaDistribution: [
    { target_persona: "垂直探路者", note_count: 36, avg_fresh_hot_score: 68.2 },
    { target_persona: "行业焦虑决策者", note_count: 28, avg_fresh_hot_score: 74.6 },
    { target_persona: "行业观望者", note_count: 18, avg_fresh_hot_score: 51.4 },
  ],
  funnelDistribution: [
    { funnel_role: "信任", note_count: 42, avg_fresh_hot_score: 58.6 },
    { funnel_role: "曝光", note_count: 29, avg_fresh_hot_score: 83.1 },
    { funnel_role: "转化", note_count: 19, avg_fresh_hot_score: 47.3 },
  ],
  industryDistribution: [
    { industry: "AI营销", note_count: 40, avg_fresh_hot_score: 62.3 },
    { industry: "数字营销", note_count: 32, avg_fresh_hot_score: 59.8 },
    { industry: "内容运营", note_count: 24, avg_fresh_hot_score: 53.1 },
  ],
  painMap: [
    {
      true_pain_label: "决策困难+效率问题",
      pain_authenticity: "真实痛点",
      note_count: 12,
      avg_fresh_hot_score: 81.4,
      example_note_ids: ["6a1ba9a10000000006031daa"],
    },
    {
      true_pain_label: "机会错失",
      pain_authenticity: "真实痛点",
      note_count: 8,
      avg_fresh_hot_score: 69.8,
      example_note_ids: ["6a637720000000001c0103b3"],
    },
  ],
  visualPatterns: [
    {
      information_density_level: "超高密度",
      visual_main_colors: "暖米黄、红色、黑色、绿色点缀",
      visual_emotion: "专业可信、知识沉淀感",
      note_count: 21,
      avg_fresh_hot_score: 76.9,
    },
    {
      information_density_level: "高密度",
      visual_main_colors: "黑黄撞色、白色正文",
      visual_emotion: "警示、避坑、紧迫感",
      note_count: 14,
      avg_fresh_hot_score: 70.1,
    },
  ],
  recentRuns: [
    {
      run_id: 96,
      note_id: "6a637720000000001c0103b3",
      model_name: "doubao-seed-2-0-mini-260428",
      status: "success",
      latency_ms: 50002,
      created_at: "2026-08-04T02:06:17.122Z",
    },
  ],
  failedQueue: [
    {
      note_id: "pending-recharge",
      error_preview: "Endata 返回：当前账户余额不足，请充值后重试失败详情任务",
    },
  ],
  ops: {
    overview: {
      apiCallsTotal: 1219,
      apiCallsFailed: 139,
      totalTokens: 1018740,
      runningScripts: 2,
      activeProviders: 6,
      activeModels: 4,
    },
    apiStatusSummary: [
      {
        provider_code: "endata_xhs_note_detail",
        display_name_cn: "艺恩详情 API 调用",
        provider_type: "detail_api",
        billing_unit: "call",
        calls_total: 200,
        calls_success: 90,
        calls_failed: 110,
        notes_total: 200,
        notes_success: 90,
        notes_failed: 110,
        total_tokens: 0,
        avg_latency_ms: 980,
        latest_started_at: "2026-08-04T02:07:57.000Z",
      },
      {
        provider_code: "volcengine_ark_vision",
        display_name_cn: "火山 Ark 图片多模态解析",
        provider_type: "llm_vision",
        billing_unit: "image_or_token",
        calls_total: 834,
        calls_success: 811,
        calls_failed: 23,
        notes_total: 90,
        notes_success: 90,
        notes_failed: 8,
        total_tokens: 0,
        avg_latency_ms: 4300,
        latest_started_at: "2026-08-04T02:05:10.000Z",
      },
      {
        provider_code: "kimi_chat",
        display_name_cn: "Kimi 内容资产总结",
        provider_type: "llm_chat",
        billing_unit: "token",
        calls_total: 96,
        calls_success: 90,
        calls_failed: 6,
        notes_total: 90,
        notes_success: 90,
        notes_failed: 3,
        total_tokens: 1018740,
        avg_latency_ms: 50000,
        latest_started_at: "2026-08-04T02:06:17.122Z",
      },
      {
        provider_code: "volcengine_ark_chat",
        display_name_cn: "火山 Ark 豆包内容资产总结",
        provider_type: "llm_chat",
        billing_unit: "token",
        calls_total: 1,
        calls_success: 1,
        calls_failed: 0,
        notes_total: 1,
        notes_success: 1,
        notes_failed: 0,
        total_tokens: 13246,
        avg_latency_ms: 48200,
        latest_started_at: "2026-08-04T06:30:20.000Z",
      },
      {
        provider_code: "volcengine_ark_embedding",
        display_name_cn: "火山 Ark Embedding",
        provider_type: "embedding",
        billing_unit: "token",
        calls_total: 90,
        calls_success: 90,
        calls_failed: 0,
        notes_total: 90,
        notes_success: 90,
        notes_failed: 0,
        total_tokens: 0,
        avg_latency_ms: 900,
        latest_started_at: "2026-08-04T02:07:11.000Z",
      },
    ],
    recentApiCalls: [
      {
        api_call_id: 1220,
        provider_code: "endata_xhs_note_detail",
        display_name_cn: "艺恩详情 API 调用",
        provider_type: "detail_api",
        operation: "historical_note_detail_fetch",
        status: "failed",
        http_status: null,
        note_id: "6953d08200000000210310da",
        note_title: "",
        model_name: "",
        started_at: "2026-08-04T02:07:57.000Z",
        latency_ms: null,
        total_tokens: null,
        error_code: "historical_business_status",
        error_message: "Code=500 Msg=当前账户余额不足，请确认",
      },
      {
        api_call_id: 1219,
        provider_code: "kimi_chat",
        display_name_cn: "Kimi 内容资产总结",
        provider_type: "llm_chat",
        operation: "historical_content_asset_summary",
        status: "success",
        http_status: 200,
        note_id: "6a637720000000001c0103b3",
        note_title: "别再只做SEO，GEO才是AI新流量",
        model_name: "kimi-k2.6",
        started_at: "2026-08-04T02:06:17.122Z",
        latency_ms: 50002,
        total_tokens: 10620,
        error_code: null,
        error_message: null,
      },
    ],
    apiFailureReasons: [
      {
        provider_code: "endata_xhs_note_detail",
        status: "failed",
        error_code: "historical_business_status",
        error_message: "Code=500 Msg=当前账户余额不足，请确认",
        count: 86,
        first_started_at: "2026-08-04T00:01:45.000Z",
        latest_started_at: "2026-08-04T02:07:57.000Z",
      },
      {
        provider_code: "endata_xhs_note_detail",
        status: "failed",
        error_code: "historical_business_status",
        error_message: "Code=500 Msg=请求失败，请重试",
        count: 24,
        first_started_at: "2026-08-04T00:05:12.000Z",
        latest_started_at: "2026-08-04T01:38:21.000Z",
      },
    ],
    apiUsage: {
      hourly: [
        { bucket_start: "2026-08-04T00:00:00.000Z", provider_code: "endata_xhs_note_detail", display_name_cn: "Endata", provider_type: "detail_api", operation: "historical_note_detail_fetch", calls_total: 70, calls_success: 35, calls_failed: 35, total_tokens: 0 },
        { bucket_start: "2026-08-04T01:00:00.000Z", provider_code: "volcengine_ark_vision", display_name_cn: "Ark Vision", provider_type: "llm_vision", model_name: "doubao-seed-2-0-mini-260428", model_role: "llm_vision", operation: "historical_image_analysis", calls_total: 420, calls_success: 410, calls_failed: 10, total_tokens: 0 },
        { bucket_start: "2026-08-04T02:00:00.000Z", provider_code: "kimi_chat", display_name_cn: "Kimi", provider_type: "llm_chat", model_name: "kimi-k2.6", model_role: "llm_chat", operation: "historical_content_asset_summary", calls_total: 96, calls_success: 90, calls_failed: 6, total_tokens: 1018740 },
        { bucket_start: "2026-08-04T02:00:00.000Z", provider_code: "volcengine_ark_embedding", display_name_cn: "Ark Embedding", provider_type: "embedding", model_name: "doubao-embedding-vision-251215", model_role: "embedding", operation: "historical_asset_embedding", calls_total: 90, calls_success: 90, calls_failed: 0, total_tokens: 0 },
      ],
      daily: [
        { bucket_start: "2026-08-03T00:00:00.000Z", provider_code: "endata_xhs_note_detail", display_name_cn: "Endata", provider_type: "detail_api", operation: "historical_note_detail_fetch", calls_total: 120, calls_success: 55, calls_failed: 65, total_tokens: 0 },
        { bucket_start: "2026-08-03T00:00:00.000Z", provider_code: "volcengine_ark_vision", display_name_cn: "Ark Vision", provider_type: "llm_vision", model_name: "doubao-seed-2-0-mini-260428", model_role: "llm_vision", operation: "historical_image_analysis", calls_total: 414, calls_success: 401, calls_failed: 13, total_tokens: 0 },
        { bucket_start: "2026-08-04T00:00:00.000Z", provider_code: "kimi_chat", display_name_cn: "Kimi", provider_type: "llm_chat", model_name: "kimi-k2.6", model_role: "llm_chat", operation: "historical_content_asset_summary", calls_total: 96, calls_success: 90, calls_failed: 6, total_tokens: 1018740 },
        { bucket_start: "2026-08-04T00:00:00.000Z", provider_code: "volcengine_ark_embedding", display_name_cn: "Ark Embedding", provider_type: "embedding", model_name: "doubao-embedding-vision-251215", model_role: "embedding", operation: "historical_asset_embedding", calls_total: 90, calls_success: 90, calls_failed: 0, total_tokens: 0 },
      ],
      weekly: [],
    },
    modelUsageSummary: [
      { model_name: "kimi-k2.6", display_name_cn: "Kimi K2.6 历史内容资产总结", provider_code: "kimi_chat", provider_type: "llm_chat", model_role: "llm_chat", calls_total: 96, calls_failed: 6, total_tokens: 1018740 },
      { model_name: "doubao-seed-2-0-mini-260428", display_name_cn: "豆包 Seed 2.0 Mini 内容资产总结", provider_code: "volcengine_ark_chat", provider_type: "llm_chat", model_role: "llm_chat", calls_total: 1, calls_failed: 0, total_tokens: 13246 },
      { model_name: "doubao-seed-2-0-mini-260428", display_name_cn: "豆包图片多模态解析", provider_code: "volcengine_ark_vision", provider_type: "llm_vision", model_role: "llm_vision", calls_total: 834, calls_failed: 23, total_tokens: 0 },
      { model_name: "doubao-embedding-vision-251215", display_name_cn: "豆包内容资产 Embedding", provider_code: "volcengine_ark_embedding", provider_type: "embedding", model_role: "embedding", calls_total: 90, calls_failed: 0, total_tokens: 0 },
    ],
    scriptRunSummary: [
      { script_key: "watch_geo_note_ingest_queue", display_name_cn: "笔记队列常驻 worker", description_cn: "监听 geo_note_ingest_queue，新 note_id 自动触发完整处理链路。", service_name: "xhs-geo-note-ingest-queue.service", is_active: true, runs_total: 3, running_count: 1, failed_count: 0, latest_status: "running", latest_started_at: "2026-08-04T04:48:57.000Z" },
      { script_key: "embed_geo_content_assets", display_name_cn: "内容资产向量刷新", description_cn: "调用 Ark embedding，把 asset_text 写入 pgvector。", service_name: "xhs-geo-asset-vector.service", is_active: true, runs_total: 3, running_count: 1, failed_count: 0, latest_status: "running", latest_started_at: "2026-08-04T04:48:57.000Z" },
    ],
    recentScriptRuns: [
      { script_run_id: 402, script_key: "watch_geo_note_ingest_queue", display_name_cn: "笔记队列常驻 worker", status: "running", trigger_type: "watch", started_at: "2026-08-04T04:48:57.000Z", duration_ms: null, success_count: null, failed_count: null },
      { script_run_id: 401, script_key: "embed_geo_content_assets", display_name_cn: "内容资产向量刷新", status: "running", trigger_type: "watch", started_at: "2026-08-04T04:48:57.000Z", duration_ms: null, success_count: null, failed_count: null },
    ],
    scriptEvents: [
      { event_id: 202, script_key: "watch_geo_note_ingest_queue", display_name_cn: "笔记队列常驻 worker", event_time: "2026-08-04T04:48:57.000Z", level: "info", event_type: "enqueue_existing", message: "历史笔记入队完成", payload: { count: 0 } },
    ],
    endataBalance: {
      latestSnapshots: [
        { range_key: "today", begin_code: "20260804", end_code: "20260804", sampled_at: "2026-08-04T06:36:00.000Z", ok: true, residue_fee: 9992.56, previous_residue_fee: 9992.57, balance_delta: -0.01, success_count: 7681, previous_success_count: 7680, success_count_delta: 1, snapshot_count: 120, latency_ms: 420 },
        { range_key: "month", begin_code: "20260801", end_code: "20260804", sampled_at: "2026-08-04T06:35:00.000Z", ok: true, residue_fee: 9992.56, previous_residue_fee: 9992.58, balance_delta: -0.02, success_count: 14320, previous_success_count: 14318, success_count_delta: 2, snapshot_count: 420, latency_ms: 460 },
      ],
      endpoints: [
        {
          url: "/v2/xhs/getstandardnoteinfo",
          display_name_cn: "艺恩详情 API 调用",
          description_cn: "按 note_id 拉取标题、正文、发布时间、互动量、图片和视频封面；通常由笔记全流程编排在缺少成功详情时调用一次。",
          count: 6925,
          previous_count: 6924,
          count_delta: 1,
          share_pct: 90.16,
          sampled_at: "2026-08-04T06:36:00.000Z",
          scripts: [
            { script_key: "watch_geo_note_ingest_queue", display_name_cn: "GEO 笔记队列 worker", scope: "GEO 新笔记入库" },
            { script_key: "sync_xhs_note_by_id", display_name_cn: "笔记全流程编排（缺详情才调艺恩）", scope: "GEO 单条补全" },
            { script_key: "xhs_author_pipeline", display_name_cn: "麦富迪作者管线", scope: "麦富迪作者笔记详情" },
          ],
        },
        {
          url: "/v2/xhs/getstandardusernotelist",
          display_name_cn: "账号笔记列表",
          description_cn: "按小红书作者/账号分页拉取笔记列表，用于发现账号近期内容和后续详情抓取。",
          count: 477,
          previous_count: 477,
          count_delta: 0,
          share_pct: 6.21,
          sampled_at: "2026-08-04T06:36:00.000Z",
          scripts: [{ script_key: "xhs_author_pipeline", display_name_cn: "麦富迪作者管线", scope: "按作者拉取笔记列表" }],
        },
        {
          url: "/v2/xhs/getxhsnotelist_gb",
          display_name_cn: "品牌/关键词笔记列表",
          description_cn: "按品牌词或关键词拉取小红书笔记列表，用于麦富迪品牌池和爆文候选发现。",
          count: 279,
          previous_count: 279,
          count_delta: 0,
          share_pct: 3.63,
          sampled_at: "2026-08-04T06:36:00.000Z",
          scripts: [{ script_key: "sync_xhs_maifudi_notes", display_name_cn: "麦富迪品牌笔记同步", scope: "按品牌/关键词拉取候选笔记" }],
        },
        {
          url: "/v2/xhs/getstandardcommentinfo",
          display_name_cn: "小红书笔记评论信息",
          description_cn: "按笔记拉取评论相关数据，用于判断评论区情绪反馈、争议点和可复用互动钩子；目前该路径只在艺恩余额快照中出现，具体调用脚本需要接入网关日志后精确归因。",
          count: 17,
          previous_count: 17,
          count_delta: 0,
          share_pct: 0.22,
          sampled_at: "2026-08-04T06:36:00.000Z",
          scripts: [{ script_key: "untracked_endata_comment_consumer", display_name_cn: "未接入网关的评论抓取", scope: "余额快照已记录消耗，等待脚本接入 geo_ops_api_call_logs" }],
        },
      ],
      endpointHistory: [
        { bucket_start: "2026-08-04T06:34:00.000Z", url: "/v2/xhs/getstandardnoteinfo", display_name_cn: "艺恩详情 API 调用", count: 6923, share_pct: 90.16 },
        { bucket_start: "2026-08-04T06:35:00.000Z", url: "/v2/xhs/getstandardnoteinfo", display_name_cn: "艺恩详情 API 调用", count: 6924, share_pct: 90.16 },
        { bucket_start: "2026-08-04T06:36:00.000Z", url: "/v2/xhs/getstandardnoteinfo", display_name_cn: "艺恩详情 API 调用", count: 6925, share_pct: 90.16 },
        { bucket_start: "2026-08-04T06:34:00.000Z", url: "/v2/xhs/getstandardusernotelist", display_name_cn: "账号笔记列表", count: 477, share_pct: 6.21 },
        { bucket_start: "2026-08-04T06:35:00.000Z", url: "/v2/xhs/getstandardusernotelist", display_name_cn: "账号笔记列表", count: 477, share_pct: 6.21 },
        { bucket_start: "2026-08-04T06:36:00.000Z", url: "/v2/xhs/getstandardusernotelist", display_name_cn: "账号笔记列表", count: 477, share_pct: 6.21 },
        { bucket_start: "2026-08-04T06:34:00.000Z", url: "/v2/xhs/getxhsnotelist_gb", display_name_cn: "品牌/关键词笔记列表", count: 279, share_pct: 3.63 },
        { bucket_start: "2026-08-04T06:35:00.000Z", url: "/v2/xhs/getxhsnotelist_gb", display_name_cn: "品牌/关键词笔记列表", count: 279, share_pct: 3.63 },
        { bucket_start: "2026-08-04T06:36:00.000Z", url: "/v2/xhs/getxhsnotelist_gb", display_name_cn: "品牌/关键词笔记列表", count: 279, share_pct: 3.63 },
        { bucket_start: "2026-08-04T06:34:00.000Z", url: "/v2/xhs/getstandardcommentinfo", display_name_cn: "小红书笔记评论信息", count: 17, share_pct: 0.22 },
        { bucket_start: "2026-08-04T06:35:00.000Z", url: "/v2/xhs/getstandardcommentinfo", display_name_cn: "小红书笔记评论信息", count: 17, share_pct: 0.22 },
        { bucket_start: "2026-08-04T06:36:00.000Z", url: "/v2/xhs/getstandardcommentinfo", display_name_cn: "小红书笔记评论信息", count: 17, share_pct: 0.22 },
      ],
      scriptUsageHourly: [
        { bucket_start: "2026-08-04T04:00:00.000Z", script_key: "watch_geo_note_ingest_queue", display_name_cn: "GEO 笔记队列 worker", url: "/v2/xhs/getstandardnoteinfo", endpoint_display_name_cn: "艺恩详情 API 调用", operation: "note_detail_fetch", calls_total: 6, calls_success: 6, calls_failed: 0 },
        { bucket_start: "2026-08-04T05:00:00.000Z", script_key: "watch_geo_note_ingest_queue", display_name_cn: "GEO 笔记队列 worker", url: "/v2/xhs/getstandardnoteinfo", endpoint_display_name_cn: "艺恩详情 API 调用", operation: "note_detail_fetch", calls_total: 11, calls_success: 10, calls_failed: 1 },
        { bucket_start: "2026-08-04T06:00:00.000Z", script_key: "sync_xhs_maifudi_notes", display_name_cn: "麦富迪品牌笔记同步", url: "/v2/xhs/getxhsnotelist_gb", endpoint_display_name_cn: "品牌/关键词笔记列表", operation: "brand_note_list_fetch", calls_total: 3, calls_success: 3, calls_failed: 0 },
      ],
    },
    modelConfigs: [
      { model_config_id: 1, provider_code: "kimi_chat", provider_display_name_cn: "Kimi 历史内容资产总结", model_name: "kimi-k2.6", display_name_cn: "Kimi K2.6 历史内容资产总结", model_role: "llm_chat", is_default: false, is_active: false, temperature: 0.6, thinking_mode: "disabled" },
      { model_config_id: 2, provider_code: "volcengine_ark_chat", provider_display_name_cn: "豆包内容资产总结", model_name: "doubao-seed-2-0-mini-260428", display_name_cn: "豆包 Seed 2.0 Mini 内容资产总结", model_role: "llm_chat", is_default: true, is_active: true, temperature: 0.6, thinking_mode: "disabled" },
      { model_config_id: 3, provider_code: "volcengine_ark_vision", provider_display_name_cn: "火山 Ark 图片多模态解析", model_name: "doubao-seed-2-0-mini-260428", display_name_cn: "豆包图片多模态解析", model_role: "llm_vision", is_default: true, is_active: true, thinking_mode: "disabled" },
      { model_config_id: 4, provider_code: "volcengine_ark_embedding", provider_display_name_cn: "火山 Ark Embedding", model_name: "doubao-embedding-vision-251215", display_name_cn: "豆包内容资产 Embedding", model_role: "embedding", is_default: true, is_active: true, dimensions: 2048 },
    ],
    credentials: [
      { credential_id: 1, provider_code: "endata_xhs_note_detail", provider_display_name_cn: "艺恩详情 API 调用", credential_name: "艺恩 Endata 默认 Token", secret_ref: "ENDATA_TOKEN", secret_mask: "ENDATA_TOKEN", status: "active", is_default: true },
      { credential_id: 2, provider_code: "kimi_chat", provider_display_name_cn: "Kimi 历史内容资产总结", credential_name: "Kimi 历史 Key", secret_ref: "KIMI_API_KEY", secret_mask: "KIMI_API_KEY", status: "disabled", is_default: false },
      { credential_id: 4, provider_code: "volcengine_ark_chat", provider_display_name_cn: "豆包内容资产总结", credential_name: "豆包内容资产总结 Key", secret_ref: "GEO_CONTENT_API_KEY", secret_mask: "GEO_CONTENT_API_KEY", status: "active", is_default: true },
      { credential_id: 3, provider_code: "volcengine_ark_vision", provider_display_name_cn: "火山 Ark 图片多模态解析", credential_name: "Ark 默认 Key", secret_ref: "ARK_API_KEY", secret_mask: "ARK_API_KEY", status: "active", is_default: true },
    ],
    rateLimitRules: [],
  },
};
