export const sampleDashboard = {
  source: "sample",
  generatedAt: new Date().toISOString(),
  overview: {
    noteDetailSuccess: 90,
    noteDetailFailed: 110,
    assetSuccess: 90,
    vectorCount: 90,
    kimiSuccessRuns: 90,
    kimiFailedRuns: 6,
    minPublishTime: "2024-11-08T00:00:00.000Z",
    maxPublishTime: "2026-07-31T00:00:00.000Z",
  },
  queueStatus: [{ status: "success", count: 199 }],
  topFresh: [
    {
      note_id: "6a1ba9a10000000006031daa",
      title: "每天拆解一个运营知识-GEO排名优化",
      publish_time: "2026-05-31T00:00:00.000Z",
      interaction_score: 968,
      fresh_hot_score: 361.2,
      true_pain_label: "决策困难+效率问题",
      primary_target_persona: "垂直探路者",
      target_persona_tags: ["垂直探路者", "行业观望者", "行业焦虑决策者"],
      primary_industry: "数字营销/内容运营",
      industry_tags: ["数字营销", "内容运营", "AI营销", "MarTech"],
      funnel_role: "信任",
    },
    {
      note_id: "6a637720000000001c0103b3",
      title: "别再只做SEO，GEO才是AI新流量",
      publish_time: "2026-07-19T00:00:00.000Z",
      interaction_score: 42,
      fresh_hot_score: 11.0,
      true_pain_label: "机会错失",
      primary_target_persona: "行业观望者",
      target_persona_tags: ["认知小白", "行业观望者"],
      primary_industry: "AI营销",
      industry_tags: ["AI营销", "品牌营销"],
      funnel_role: "曝光",
    },
  ],
  personaDistribution: [
    { target_persona: "垂直探路者", note_count: 36, avg_fresh_hot_score: 68.2 },
    { target_persona: "行业焦虑决策者", note_count: 28, avg_fresh_hot_score: 74.6 },
    { target_persona: "行业观望者", note_count: 18, avg_fresh_hot_score: 51.4 },
  ],
  funnelDistribution: [
    { funnel_role: "信任", note_count: 42, avg_fresh_hot_score: 58.6 },
    { funnel_role: "曝光", note_count: 29, avg_fresh_hot_score: 83.1 },
    { funnel_role: "转化", note_count: 19, avg_fresh_hot_score: 47.3 },
  ],
  industryDistribution: [
    { industry: "AI营销", note_count: 40, avg_fresh_hot_score: 62.3 },
    { industry: "数字营销", note_count: 32, avg_fresh_hot_score: 59.8 },
    { industry: "内容运营", note_count: 24, avg_fresh_hot_score: 53.1 },
  ],
  painMap: [
    {
      true_pain_label: "决策困难+效率问题",
      pain_authenticity: "真实痛点",
      note_count: 12,
      avg_fresh_hot_score: 81.4,
      example_note_ids: ["6a1ba9a10000000006031daa"],
    },
    {
      true_pain_label: "机会错失",
      pain_authenticity: "真实痛点",
      note_count: 8,
      avg_fresh_hot_score: 69.8,
      example_note_ids: ["6a637720000000001c0103b3"],
    },
  ],
  visualPatterns: [
    {
      information_density_level: "超高密度",
      visual_main_colors: "暖米黄、红色、黑色、绿色点缀",
      visual_emotion: "专业可信、知识沉淀感",
      note_count: 21,
      avg_fresh_hot_score: 76.9,
    },
    {
      information_density_level: "高密度",
      visual_main_colors: "黑黄撞色、白色正文",
      visual_emotion: "警示、避坑、紧迫感",
      note_count: 14,
      avg_fresh_hot_score: 70.1,
    },
  ],
  recentRuns: [
    {
      run_id: 96,
      note_id: "6a637720000000001c0103b3",
      model_name: "kimi-k2.6",
      status: "success",
      latency_ms: 50002,
      created_at: "2026-08-04T02:06:17.122Z",
    },
  ],
  failedQueue: [
    {
      note_id: "pending-recharge",
      error_preview: "Endata 返回：当前账户余额不足，请充值后重试失败详情任务",
    },
  ],
  ops: {
    overview: {
      apiCallsTotal: 1219,
      apiCallsFailed: 139,
      totalTokens: 1018740,
      runningScripts: 2,
      activeProviders: 6,
      activeModels: 3,
    },
    apiStatusSummary: [
      {
        provider_code: "endata_xhs_note_detail",
        display_name_cn: "Endata 小红书笔记详情",
        provider_type: "detail_api",
        billing_unit: "call",
        calls_total: 200,
        calls_success: 90,
        calls_failed: 110,
        notes_total: 200,
        notes_success: 90,
        notes_failed: 110,
        total_tokens: 0,
        avg_latency_ms: 980,
        latest_started_at: "2026-08-04T02:07:57.000Z",
      },
      {
        provider_code: "volcengine_ark_vision",
        display_name_cn: "火山 Ark 图片多模态解析",
        provider_type: "llm_vision",
        billing_unit: "image_or_token",
        calls_total: 834,
        calls_success: 811,
        calls_failed: 23,
        notes_total: 90,
        notes_success: 90,
        notes_failed: 8,
        total_tokens: 0,
        avg_latency_ms: 4300,
        latest_started_at: "2026-08-04T02:05:10.000Z",
      },
      {
        provider_code: "kimi_chat",
        display_name_cn: "Kimi 内容资产总结",
        provider_type: "llm_chat",
        billing_unit: "token",
        calls_total: 96,
        calls_success: 90,
        calls_failed: 6,
        notes_total: 90,
        notes_success: 90,
        notes_failed: 3,
        total_tokens: 1018740,
        avg_latency_ms: 50000,
        latest_started_at: "2026-08-04T02:06:17.122Z",
      },
      {
        provider_code: "volcengine_ark_chat",
        display_name_cn: "火山 Ark 豆包内容资产总结",
        provider_type: "llm_chat",
        billing_unit: "token",
        calls_total: 1,
        calls_success: 1,
        calls_failed: 0,
        notes_total: 1,
        notes_success: 1,
        notes_failed: 0,
        total_tokens: 13246,
        avg_latency_ms: 48200,
        latest_started_at: "2026-08-04T06:30:20.000Z",
      },
      {
        provider_code: "volcengine_ark_embedding",
        display_name_cn: "火山 Ark Embedding",
        provider_type: "embedding",
        billing_unit: "token",
        calls_total: 90,
        calls_success: 90,
        calls_failed: 0,
        notes_total: 90,
        notes_success: 90,
        notes_failed: 0,
        total_tokens: 0,
        avg_latency_ms: 900,
        latest_started_at: "2026-08-04T02:07:11.000Z",
      },
    ],
    recentApiCalls: [
      {
        api_call_id: 1220,
        provider_code: "endata_xhs_note_detail",
        display_name_cn: "Endata 小红书笔记详情",
        provider_type: "detail_api",
        operation: "historical_note_detail_fetch",
        status: "failed",
        http_status: null,
        note_id: "6953d08200000000210310da",
        note_title: "",
        model_name: "",
        started_at: "2026-08-04T02:07:57.000Z",
        latency_ms: null,
        total_tokens: null,
        error_code: "historical_business_status",
        error_message: "Code=500 Msg=当前账户余额不足，请确认",
      },
      {
        api_call_id: 1219,
        provider_code: "kimi_chat",
        display_name_cn: "Kimi 内容资产总结",
        provider_type: "llm_chat",
        operation: "historical_content_asset_summary",
        status: "success",
        http_status: 200,
        note_id: "6a637720000000001c0103b3",
        note_title: "别再只做SEO，GEO才是AI新流量",
        model_name: "kimi-k2.6",
        started_at: "2026-08-04T02:06:17.122Z",
        latency_ms: 50002,
        total_tokens: 10620,
        error_code: null,
        error_message: null,
      },
    ],
    apiFailureReasons: [
      {
        provider_code: "endata_xhs_note_detail",
        status: "failed",
        error_code: "historical_business_status",
        error_message: "Code=500 Msg=当前账户余额不足，请确认",
        count: 86,
        first_started_at: "2026-08-04T00:01:45.000Z",
        latest_started_at: "2026-08-04T02:07:57.000Z",
      },
      {
        provider_code: "endata_xhs_note_detail",
        status: "failed",
        error_code: "historical_business_status",
        error_message: "Code=500 Msg=请求失败，请重试",
        count: 24,
        first_started_at: "2026-08-04T00:05:12.000Z",
        latest_started_at: "2026-08-04T01:38:21.000Z",
      },
    ],
    apiUsage: {
      hourly: [
        { bucket_start: "2026-08-04T00:00:00.000Z", provider_code: "endata_xhs_note_detail", display_name_cn: "Endata", provider_type: "detail_api", operation: "historical_note_detail_fetch", calls_total: 70, calls_success: 35, calls_failed: 35, total_tokens: 0 },
        { bucket_start: "2026-08-04T01:00:00.000Z", provider_code: "volcengine_ark_vision", display_name_cn: "Ark Vision", provider_type: "llm_vision", model_name: "doubao-seed-2-0-mini-260428", model_role: "llm_vision", operation: "historical_image_analysis", calls_total: 420, calls_success: 410, calls_failed: 10, total_tokens: 0 },
        { bucket_start: "2026-08-04T02:00:00.000Z", provider_code: "kimi_chat", display_name_cn: "Kimi", provider_type: "llm_chat", model_name: "kimi-k2.6", model_role: "llm_chat", operation: "historical_content_asset_summary", calls_total: 96, calls_success: 90, calls_failed: 6, total_tokens: 1018740 },
        { bucket_start: "2026-08-04T02:00:00.000Z", provider_code: "volcengine_ark_embedding", display_name_cn: "Ark Embedding", provider_type: "embedding", model_name: "doubao-embedding-vision-251215", model_role: "embedding", operation: "historical_asset_embedding", calls_total: 90, calls_success: 90, calls_failed: 0, total_tokens: 0 },
      ],
      daily: [
        { bucket_start: "2026-08-03T00:00:00.000Z", provider_code: "endata_xhs_note_detail", display_name_cn: "Endata", provider_type: "detail_api", operation: "historical_note_detail_fetch", calls_total: 120, calls_success: 55, calls_failed: 65, total_tokens: 0 },
        { bucket_start: "2026-08-03T00:00:00.000Z", provider_code: "volcengine_ark_vision", display_name_cn: "Ark Vision", provider_type: "llm_vision", model_name: "doubao-seed-2-0-mini-260428", model_role: "llm_vision", operation: "historical_image_analysis", calls_total: 414, calls_success: 401, calls_failed: 13, total_tokens: 0 },
        { bucket_start: "2026-08-04T00:00:00.000Z", provider_code: "kimi_chat", display_name_cn: "Kimi", provider_type: "llm_chat", model_name: "kimi-k2.6", model_role: "llm_chat", operation: "historical_content_asset_summary", calls_total: 96, calls_success: 90, calls_failed: 6, total_tokens: 1018740 },
        { bucket_start: "2026-08-04T00:00:00.000Z", provider_code: "volcengine_ark_embedding", display_name_cn: "Ark Embedding", provider_type: "embedding", model_name: "doubao-embedding-vision-251215", model_role: "embedding", operation: "historical_asset_embedding", calls_total: 90, calls_success: 90, calls_failed: 0, total_tokens: 0 },
      ],
      weekly: [],
    },
    modelUsageSummary: [
      { model_name: "kimi-k2.6", display_name_cn: "Kimi K2.6 内容资产总结", provider_code: "kimi_chat", provider_type: "llm_chat", model_role: "llm_chat", calls_total: 96, calls_failed: 6, total_tokens: 1018740 },
      { model_name: "doubao-seed-2-0-mini-260428", display_name_cn: "豆包图片多模态解析", provider_code: "volcengine_ark_vision", provider_type: "llm_vision", model_role: "llm_vision", calls_total: 834, calls_failed: 23, total_tokens: 0 },
      { model_name: "doubao-embedding-vision-251215", display_name_cn: "豆包内容资产 Embedding", provider_code: "volcengine_ark_embedding", provider_type: "embedding", model_role: "embedding", calls_total: 90, calls_failed: 0, total_tokens: 0 },
    ],
    scriptRunSummary: [
      { script_key: "watch_geo_note_ingest_queue", display_name_cn: "笔记队列常驻 worker", description_cn: "监听 geo_note_ingest_queue，新 note_id 自动触发完整处理链路。", service_name: "xhs-geo-note-ingest-queue.service", is_active: true, runs_total: 3, running_count: 1, failed_count: 0, latest_status: "running", latest_started_at: "2026-08-04T04:48:57.000Z" },
      { script_key: "embed_geo_content_assets", display_name_cn: "内容资产向量刷新", description_cn: "调用 Ark embedding，把 asset_text 写入 pgvector。", service_name: "xhs-geo-asset-vector.service", is_active: true, runs_total: 3, running_count: 1, failed_count: 0, latest_status: "running", latest_started_at: "2026-08-04T04:48:57.000Z" },
    ],
    recentScriptRuns: [
      { script_run_id: 402, script_key: "watch_geo_note_ingest_queue", display_name_cn: "笔记队列常驻 worker", status: "running", trigger_type: "watch", started_at: "2026-08-04T04:48:57.000Z", duration_ms: null, success_count: null, failed_count: null },
      { script_run_id: 401, script_key: "embed_geo_content_assets", display_name_cn: "内容资产向量刷新", status: "running", trigger_type: "watch", started_at: "2026-08-04T04:48:57.000Z", duration_ms: null, success_count: null, failed_count: null },
    ],
    scriptEvents: [
      { event_id: 202, script_key: "watch_geo_note_ingest_queue", display_name_cn: "笔记队列常驻 worker", event_time: "2026-08-04T04:48:57.000Z", level: "info", event_type: "enqueue_existing", message: "历史笔记入队完成", payload: { count: 0 } },
    ],
    modelConfigs: [
      { model_config_id: 1, provider_code: "kimi_chat", provider_display_name_cn: "Kimi 内容资产总结", model_name: "kimi-k2.6", display_name_cn: "Kimi K2.6 内容资产总结", model_role: "llm_chat", is_default: true, is_active: true, temperature: 0.6, thinking_mode: "disabled" },
      { model_config_id: 3, provider_code: "volcengine_ark_vision", provider_display_name_cn: "火山 Ark 图片多模态解析", model_name: "doubao-seed-2-0-mini-260428", display_name_cn: "豆包图片多模态解析", model_role: "llm_vision", is_default: true, is_active: true, thinking_mode: "disabled" },
      { model_config_id: 4, provider_code: "volcengine_ark_embedding", provider_display_name_cn: "火山 Ark Embedding", model_name: "doubao-embedding-vision-251215", display_name_cn: "豆包内容资产 Embedding", model_role: "embedding", is_default: true, is_active: true, dimensions: 2048 },
    ],
    credentials: [
      { credential_id: 1, provider_code: "endata_xhs_note_detail", provider_display_name_cn: "Endata 小红书笔记详情", credential_name: "Endata 默认 Token", secret_ref: "ENDATA_TOKEN", secret_mask: "ENDATA_TOKEN", status: "active", is_default: true },
      { credential_id: 2, provider_code: "kimi_chat", provider_display_name_cn: "Kimi 内容资产总结", credential_name: "Kimi 默认 Key", secret_ref: "KIMI_API_KEY", secret_mask: "KIMI_API_KEY", status: "active", is_default: true },
      { credential_id: 3, provider_code: "volcengine_ark_vision", provider_display_name_cn: "火山 Ark 图片多模态解析", credential_name: "Ark 默认 Key", secret_ref: "ARK_API_KEY", secret_mask: "ARK_API_KEY", status: "active", is_default: true },
    ],
    rateLimitRules: [],
  },
};
