export const sampleDashboard = {
  source: "sample",
  generatedAt: new Date().toISOString(),
  overview: {
    noteDetailSuccess: 90,
    noteDetailFailed: 110,
    assetSuccess: 90,
    vectorCount: 90,
    kimiSuccessRuns: 90,
    kimiFailedRuns: 6,
    minPublishTime: "2024-11-08T00:00:00.000Z",
    maxPublishTime: "2026-07-31T00:00:00.000Z",
  },
  queueStatus: [{ status: "success", count: 199 }],
  topFresh: [
    {
      note_id: "6a1ba9a10000000006031daa",
      title: "每天拆解一个运营知识—GEO排名优化",
      publish_time: "2026-05-31T00:00:00.000Z",
      interaction_score: 968,
      fresh_hot_score: 361.2,
      true_pain_label: "决策困难+效率问题",
      primary_target_persona: "垂直探路者",
      target_persona_tags: ["垂直探路者", "行业观望者", "行业焦虑决策者"],
      primary_industry: "数字营销/内容运营",
      industry_tags: ["数字营销", "内容运营", "AI营销", "MarTech"],
      funnel_role: "信任",
    },
    {
      note_id: "6a637720000000001c0103b3",
      title: "别再只做SEO，GEO才是AI新流量",
      publish_time: "2026-07-19T00:00:00.000Z",
      interaction_score: 42,
      fresh_hot_score: 11.0,
      true_pain_label: "机会错失",
      primary_target_persona: "行业观望者",
      target_persona_tags: ["认知小白", "行业观望者"],
      primary_industry: "AI营销",
      industry_tags: ["AI营销", "品牌营销"],
      funnel_role: "曝光",
    },
  ],
  personaDistribution: [
    { target_persona: "垂直探路者", note_count: 36, avg_fresh_hot_score: 68.2 },
    { target_persona: "行业焦虑决策者", note_count: 28, avg_fresh_hot_score: 74.6 },
    { target_persona: "行业观望者", note_count: 18, avg_fresh_hot_score: 51.4 },
  ],
  funnelDistribution: [
    { funnel_role: "信任", note_count: 42, avg_fresh_hot_score: 58.6 },
    { funnel_role: "曝光", note_count: 29, avg_fresh_hot_score: 83.1 },
    { funnel_role: "转化", note_count: 19, avg_fresh_hot_score: 47.3 },
  ],
  industryDistribution: [
    { industry: "AI营销", note_count: 40, avg_fresh_hot_score: 62.3 },
    { industry: "数字营销", note_count: 32, avg_fresh_hot_score: 59.8 },
    { industry: "内容运营", note_count: 24, avg_fresh_hot_score: 53.1 },
  ],
  painMap: [
    {
      true_pain_label: "决策困难+效率问题",
      pain_authenticity: "真实痛点",
      note_count: 12,
      avg_fresh_hot_score: 81.4,
      example_note_ids: ["6a1ba9a10000000006031daa"],
    },
    {
      true_pain_label: "机会错失",
      pain_authenticity: "真实痛点",
      note_count: 8,
      avg_fresh_hot_score: 69.8,
      example_note_ids: ["6a637720000000001c0103b3"],
    },
  ],
  visualPatterns: [
    {
      information_density_level: "超高密度",
      visual_main_colors: "暖米黄、红色、黑色、绿色点缀",
      visual_emotion: "专业可信、知识沉淀感",
      note_count: 21,
      avg_fresh_hot_score: 76.9,
    },
    {
      information_density_level: "高密度",
      visual_main_colors: "黑黄撞色、白色正文",
      visual_emotion: "警示、避坑、紧迫感",
      note_count: 14,
      avg_fresh_hot_score: 70.1,
    },
  ],
  recentRuns: [
    {
      run_id: 96,
      note_id: "6a637720000000001c0103b3",
      model_name: "kimi-k2.6",
      status: "success",
      latency_ms: 50002,
      created_at: "2026-08-04T02:06:17.122Z",
    },
  ],
  failedQueue: [
    {
      note_id: "pending-recharge",
      error_preview: "Endata 返回：当前账户余额不足，请充值后重试失败详情任务",
    },
  ],
};
